Uco/Areas/Admin/Controllers/DiscountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Uco.Infrastructure;
using Uco.Models;
using System.Data.Entity;
using Uco.Infrastructure.Repositories;
using System.IO;
using System.Text;
using Uco.Infrastructure.Discounts;
using System.Reflection;
using Uco.Infrastructure.Livecycle;

namespace Uco.Areas.Admin.Controllers
{

    [AuthorizeAdmin]
    public class DiscountController : BaseAdminController
    {
        private DiscountService _discountService;
        public DiscountController()
        {
            _discountService = new DiscountService(_db);
        }
        public ActionResult Index()
        {
            ViewBag.MessageRed = TempData["MessageRed"];
            ViewBag.MessageYellow = TempData["MessageYellow"];
            ViewBag.MessageGreen = TempData["MessageGreen"];


            return View(new Discount());
        }
        public ActionResult NewRule(string RuleName)
        {
            var rules = DiscountService.GetRules();
            if (string.IsNullOrEmpty(RuleName) || !rules.ContainsKey(RuleName))
            {
                return Content(RP.T("Admin.Discount.RuleNotFound").ToString());
            }
            var rule = rules[RuleName];
            var model = rule.GetConfigItem();
            return PartialView(model);
        }
        [ChildActionOnly]
        public ActionResult Rules(int ID)
        {
            var lst = DiscountService.GetRules();

            var model =
                lst.Select(x => new SelectListItem()
                {
                    Text = _discountService.GetLocalizeRuleName(x.Key),
                    Value = x.Key
                }).ToList()
                ;

            return View(model);
        }
        private void MapModel(object model, string prefix = "")
        {
            var t = model.GetType();

            MethodInfo method = this.GetType().GetMethods(BindingFlags.Instance | BindingFlags.NonPublic)
                .Where(x => x.Name == "TryUpdateModel"
                    && x.GetParameters().Count() == 2
                    && x.GetParameters()[1].ParameterType == typeof(string)
                    )
                .FirstOrDefault();
            MethodInfo genericMethod = method.MakeGenericMethod(t);
            var refObject = genericMethod.Invoke(this, new object[] { model, prefix });
        }
        public ActionResult DiscountRuleList(int ID)
        {
            var discount = _db.Discounts.FirstOrDefault(x => x.ID == ID);
            if (discount != null)
            {
                var list = new List<JsonKeyObject>();
                var rules = DiscountService.GetRules();
                System.Web.Script.Serialization.JavaScriptSerializer js = new System.Web.Script.Serialization.JavaScriptSerializer();

                foreach (var r in discount.RuleList)
                {
                    if (rules.ContainsKey(r.Name))
                    {
                        var ruleprovider = rules[r.Name];
                        var confitem = ruleprovider.GetConfigItem();
                        var o = js.Deserialize(r.Value, confitem.GetType());
                        list.Add(new JsonKeyObject()
                        {
                            Name = r.Name,
                            Object = o
                        });
                    }
                }

                return PartialView(list);
            }
            return Content(RP.T("Admin.Discount.NotFound").ToString());
        }
        [HttpPost]
        public ActionResult UpdateRule(int ID, int Num, string systemName, string prefix)
        {
            var rules = DiscountService.GetRules();
            if (string.IsNullOrEmpty(systemName) || !rules.ContainsKey(systemName))
            {
                return Content(RP.T("Admin.Discount.RuleNotFound").ToString());
            }
            var rule = rules[systemName];
            var saved = rule.GetConfigItem();


            System.Web.Script.Serialization.JavaScriptSerializer js = new System.Web.Script.Serialization.JavaScriptSerializer();

            var discount = _db.Discounts.FirstOrDefault(x => x.ID == ID);
            if (discount != null)
            {

                for (var i = 1; i <= discount.RuleList.Count; i++)
                {
                    if (i == Num)
                    {
                        MapModel(saved, prefix);
                        discount.RuleList[i - 1] = new JsonKeyValue()
                        {
                            Name = systemName,
                            Value = js.Serialize(saved)
                        };
                        break;
                    }
                }
            }
            //js.Serialize();
            discount.RulesData = js.Serialize(discount.RuleList);
            _db.SaveChanges();
            return Json(new { result = "ok" });
        }
        [HttpPost]
        public ActionResult RemoveRule(int ID, int Num, string systemName, string prefix)
        {
            var rules = DiscountService.GetRules();
            if (string.IsNullOrEmpty(systemName) || !rules.ContainsKey(systemName))
            {
                return Content(RP.T("Admin.Discount.RuleNotFound").ToString());
            }
            var rule = rules[systemName];
            var saved = rule.GetConfigItem();

            MapModel(saved);
            System.Web.Script.Serialization.JavaScriptSerializer js = new System.Web.Script.Serialization.JavaScriptSerializer();

            var discount = _db.Discounts.FirstOrDefault(x => x.ID == ID);
            if (discount != null)
            {

                for (var i = 1; i <= discount.RuleList.Count; i++)
                {
                    if (i == Num)
                    {

                        discount.RuleList.RemoveAt(i - 1);
                        break;
                    }
                }
            }
            //js.Serialize();
            discount.RulesData = js.Serialize(discount.RuleList);
            _db.SaveChanges();
            return Json(new { result = "ok" });
        }

        [HttpPost]
        public ActionResult SaveNewRule(int ID, string systemName, string prefix)
        {
            var rules = DiscountService.GetRules();
            if (string.IsNullOrEmpty(systemName) || !rules.ContainsKey(systemName))
            {
                return Content(RP.T("Admin.Discount.RuleNotFound").ToString());
            }
            var rule = rules[systemName];
            var saved = rule.GetConfigItem();

            MapModel(saved, prefix);
            System.Web.Script.Serialization.JavaScriptSerializer js = new System.Web.Script.Serialization.JavaScriptSerializer();

            var discount = _db.Discounts.FirstOrDefault(x => x.ID == ID);
            if (discount != null)
            {
                discount.RuleList.Add(new JsonKeyValue()
                {
                    Name = systemName,
                    Value = js.Serialize(saved)
                });
            }
            //js.Serialize();
            discount.RulesData = js.Serialize(discount.RuleList);
            _db.SaveChanges();
            return Json(new { result = "ok" });
        }

        [HttpPost]
        public ActionResult Edit(Discount item)
        {
            var discount = _db.Discounts.FirstOrDefault(x => x.ID == item.ID);
            if (discount != null)
            {
                discount.Amount = item.Amount;
                discount.Name = item.Name;
                discount.DiscountCode = item.DiscountCode;
                discount.DiscountType = item.DiscountType;
                discount.DisplayOrder = item.DisplayOrder;
                discount.EndDate = item.EndDate;
                discount.IsCodeRequired = item.IsCodeRequired;
                discount.IsPercent = item.IsPercent;
                discount.Limit = item.Limit;
                discount.LimitType = item.LimitType;
                discount.Percent = item.Percent;
                discount.DiscountCartItemType = item.DiscountCartItemType;
                discount.PreventNext = item.PreventNext;
                discount.ShopID = item.ShopID;
                discount.StartDate = item.StartDate;
                discount.Active = item.Active;
                var oldProductShopIds = discount.ProductShopIDs;
                discount.ProductShopIDs = item.ProductShopIDs;

                if (oldProductShopIds != null)
                {
                    foreach (var prid in oldProductShopIds.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries))
                    {
                        int id = Convert.ToInt32(prid);
                        var prod = _db.ProductShopMap.FirstOrDefault(x => x.ID == id);
                        if (prod != null)
                            prod.HaveDiscount = false;
                    }
                }

                if (discount.ProductShopIDs != null)
                {
                    foreach (var prid in discount.ProductShopIDs.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries))
                    {
                        int id = Convert.ToInt32(prid);
                        var prod = _db.ProductShopMap.FirstOrDefault(x => x.ID == id);
                        if (prod != null)
                            prod.HaveDiscount = discount.Active;
                    }
                }

                _db.SaveChanges();
                LS.Clear<Discount>();
            }
            return Json(new { result = "ok", discount });
        }
    }
}

Uco/Areas/Member/Views/Discount/Create.cshtml
@model Discount
@using System.Reflection
@using System.Collections.Generic
@using System.Linq
@using System.ComponentModel.DataAnnotations
@using Uco.Models

@{
    var name = Model.GetType().Name;
    ViewBag.Title = RP.T("Admin.Views." + name + ".Create.Title");
    TempData["FilterShopID"] = Model.ShopID;
    Layout = "~/Areas/" + LS.GetArea() + "/Views/Shared/_LayoutNoTree.cshtml";
}
<h2>@RP.T("Admin.Views." + name + ".Create.Title")</h2>
@Html.Partial("_EditOrCreate", (object)Model)
@{

    return;
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.EditorForModel()
    <p class="clear">
        <input type="submit" class="k-button" value="@RP.T("Admin.Views.Command.Create")" />
        @if (ViewBag.BackUrl != null)
        {
            <a href="@ViewBag.BackUrl">@RP.T("Admin.Views.Command.BackToList")</a>

        }
        else
        {
            @Html.ActionLink(@RP.T("Admin.Views.Command.BackToList").ToString(), "Index")
        }
    </p>
}

Uco/Areas/Member/Views/Discount/DiscountRuleList.cshtml
@model List<JsonKeyObject>
@using System.Reflection
@using System.Collections.Generic
@using System.Linq
@using System.ComponentModel.DataAnnotations
@using Uco.Models
@{
    System.Type t = Model.GetType();
    var ModelName = t.Name;

    ViewBag.HideButtons = true;
    int i = 0;
}

@foreach (var rule in Model)
{
    i++;
    <div class="editrulewrap" style="margin-top:6px; padding-top:10px; border-top:1px solid #f3f3f3">
        <strong>
            @RP.T("Discount.Name." + rule.Name)
            :
        </strong>

        <div>
            @{
    var prefix = "template" + LS.GetRandom();
    ViewData.TemplateInfo.HtmlFieldPrefix = prefix;
            }
            @Html.Partial("_EditOrCreate", rule.Object)
            @{
    ViewData.TemplateInfo.HtmlFieldPrefix = "";
            }
            <input type="hidden" name="prefix" value="@prefix" />
            <input type="hidden" name="numposition" value="@i" />
            <input type="hidden" name="systemName" value="@rule.Name" />
        </div>
        <button class="k-button updateruletodiscount">@RP.T("Admin.Common.Update")</button>
        <button class="k-button ruleremove">@RP.T("Admin.Common.Remove")</button>
        <div class="status"></div>
    </div>
}

<script>
    $('.ruleremove').click(function () {
        var parent = $(this).parents('.editrulewrap:eq(0)');

        var data = $('form', parent).serialize();
        var prefix = $('input[name="prefix"]', parent).val();
        var numposition = $('input[name="numposition"]', parent).val();
        var systemName = $('input[name="systemName"]', parent).val();
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "/Member/Discount/RemoveRule/" + $('#ID').val()
                + "?prefix=" + prefix
                 + "&systemName=" + systemName
            + "&Num=" + numposition,
            data: data,
            cache: false,
            error: function () { }
        }).done(function (data) {
            parent.remove();
            refreshList();
        });

    });

    $('.updateruletodiscount').click(function () {
        var parent = $(this).parents('.editrulewrap:eq(0)');

        var data = $('form', parent).serialize();
        var prefix = $('input[name="prefix"]', parent).val();
        var numposition = $('input[name="numposition"]', parent).val();
        var systemName = $('input[name="systemName"]', parent).val();
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "/Member/Discount/UpdateRule/" + $('#ID').val()
                   + "?prefix=" + prefix
                 + "&systemName=" + systemName
            + "&Num=" + numposition,
            data: data,
            cache: false,
            error: function () { }
        }).done(function (data) {
            //  parent.remove();
            // refreshList();
            $('.status', parent).html('@RP.T("Admin.Common.UpdateSuccess")');
        });

    });
</script>
<div class="clear"></div>

Uco/Areas/Member/Views/Discount/Edit.cshtml
@model Discount
@using System.Reflection
@using System.Collections.Generic
@using System.Linq
@using System.ComponentModel.DataAnnotations
@using Uco.Models
@{
    System.Type t = Model.GetType();
    var ModelName = t.Name;
    ViewBag.Title = RP.T("Admin.Views.ProductShop.Index.Title");
    TempData["FilterShopID"] = Model.ShopID;
    Layout = "~/Areas/" + LS.GetArea() + "/Views/Shared/_LayoutNoTree.cshtml";

}
<h2>@RP.T("Admin.Views." + ModelName + ".Edit.Title")</h2>

@(Html.Kendo().TabStrip()
    .Name("TabStrip")
    .Animation(false)
    .Items(tabstrip =>
    {
        tabstrip.Add().Text(RP.T("Admin.Discount.TabMain").ToString()).Content(@<text>
            <div id="maindata">
                @Html.Partial("_EditOrCreate", Model)

                <button type="submit" id="savebutton" class="k-button">@RP.T("Admin.Views.Command.Save")</button>
                <div id="mainstatus"></div>
            </div>
        </text>);

        tabstrip.Add().Text(RP.T("Admin.Discount.TabRules").ToString()).Content(@<text>


        @Html.Action("Rules", "Discount", new { ID = Model.ID })
        </text>);


    }).SelectedIndex(0))

<script>
    /**** Toggle discount fields ****/
    var DiscountPulse = {
        wrap: '#maindata',
        toggle: function () {

            if (DiscountPulse.active()) {
                DiscountPulse.IsPercent();
                DiscountPulse.IsCodeRequired();
                DiscountPulse.LimitType();
                DiscountPulse.DiscountType();

            }
        },
        active: function () {
            var checkbox = $('#Active', $(DiscountPulse.wrap));
            var form = checkbox.parents('form:eq(0)');
            if (checkbox.is(":checked")) {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 4) { $(e).show(); }
                });
                return true;
            } else {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 4) { $(e).hide(); }
                });
            }
            return false;
        },
        IsPercent: function () {
            var checkbox = $('#IsPercent', $(DiscountPulse.wrap));
            var form = checkbox.parents('form:eq(0)');
            if (checkbox.is(":checked")) {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 6 && i <= 7) { $(e).hide(); }
                    if (i >= 8 && i <= 9) { $(e).show(); }
                });
            } else {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 6 && i <= 7) { $(e).show(); }
                    if (i >= 8 && i <= 9) { $(e).hide(); }
                });
            }
        },
        IsCodeRequired: function () {
            var checkbox = $('#IsCodeRequired', $(DiscountPulse.wrap));
            var form = checkbox.parents('form:eq(0)');
            if (checkbox.is(":checked")) {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 12 && i <= 13) { $(e).show(); }
                });
            } else {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 12 && i <= 13) { $(e).hide(); }
                });
            }
        },
        LimitType: function () {
            var checkbox = $('#LimitType', $(DiscountPulse.wrap));
            var form = checkbox.parents('form:eq(0)');
            if (checkbox.val() != '0') {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 16 && i <= 17) { $(e).show(); }
                });
            } else {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 16 && i <= 17) { $(e).hide(); }
                });
            }
        },
        DiscountType: function () {
            var checkbox = $('#DiscountType', $(DiscountPulse.wrap));
            var form = checkbox.parents('form:eq(0)');
            if (checkbox.val() == '0') {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 20 && i <= 23) { $(e).show(); }

                });
            } else {
                $('.editor-field, .editor-label', form).each(function (i, e) {
                    if (i >= 20 && i <= 23) { $(e).hide(); }
                });
            }
        },
    };
    DiscountPulse.toggle();
    $('#Active', $(DiscountPulse.wrap)).click(DiscountPulse.toggle);
    $('#IsPercent', $(DiscountPulse.wrap)).click(DiscountPulse.toggle);
    $('#IsCodeRequired', $(DiscountPulse.wrap)).click(DiscountPulse.toggle);
    $('#LimitType', $(DiscountPulse.wrap)).change(DiscountPulse.toggle);
    $('#DiscountType', $(DiscountPulse.wrap)).change(DiscountPulse.toggle);

    /**** END Toggle discount fields ****/

    $('#savebutton').click(function () {
        $('#mainstatus').html('');
        var data = $('#maindata form').serialize();
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "/Member/Discount/Edit/" + $('#ID').val(),
            data: data,
            cache: false,
            error: function () { $('#mainstatus').html('@RP.T("Admin.Common.ServerError")'); }
        }).done(function (data) {
            if (data.result == "ok") {
                $('#mainstatus').html('@RP.T("Admin.Common.SaveSuccess")');
            } else {
                //data.message - errors
                $('#mainstatus').html('@RP.T("Admin.Common.SaveError")');
            }
        });
    });


</script>

<p class="clear">
    @Html.ActionLink(@RP.T("Admin.Views.Command.BackToList").ToString(), "Index")
</p>

Uco/Areas/Member/Views/Discount/NewRule.cshtml
@model object
@using System.Reflection
@using System.Collections.Generic
@using System.Linq
@using System.ComponentModel.DataAnnotations
@using Uco.Models
@{
    System.Type t = Model.GetType();
    var ModelName = t.Name;

    ViewBag.HideButtons = true;
}
<div id="ruleaddwrap">
    @{
        var prefix = "template" + LS.GetRandom();
        ViewData.TemplateInfo.HtmlFieldPrefix = prefix;
    }
    @Html.Partial("_EditOrCreate", Model)
    @{
        ViewData.TemplateInfo.HtmlFieldPrefix = "";
    }


    <button id="saveruletodiscount" class="k-button">@RP.T("Admin.Common.Save")</button>
    <button id="rulecancel" class="k-button">@RP.T("Admin.Common.Cancel")</button>

</div>
<script>
    $('#rulecancel').click(function () {
        $('#ruleaddwrap').remove();
    });

    $('#saveruletodiscount').click(function () {
        var data = $('#ruleaddwrap form').serialize();

        $.ajax({
            type: "POST",
            dataType: "json",
            url: "/Member/Discount/SaveNewRule/" + $('#ID').val() + "?systemName=" + $('#systemName').val()
            + "&prefix=@prefix",
            data: data,
            cache: false,
            error: function () { }
        }).done(function (data) {
            refreshList();
            $('#ruleaddwrap').remove();
        });


    });
</script>
<div class="clear"></div>

Uco/Areas/Member/Views/Discount/Rules.cshtml
@model List<SelectListItem>
@using System.Reflection
@using System.Collections.Generic
@using System.Linq
@using System.ComponentModel.DataAnnotations
@using Uco.Infrastructure.Discounts

<div id="ruleadd">
    @Html.DropDownList("Rule", Model)
    <button id="addnewrule" class="k-button"> @RP.T("Admin.Common.Add") </button>
    <input id="systemName" type="hidden" value="">
</div>
<div id="newrulewrap">

</div>
<div id="rulelist">

</div>
<script>
    $('#addnewrule').click(function () {
        var data = {};
        data.RuleName = $('#Rule').val();
        $('#systemName').val(data.RuleName);
        $.ajax({
            type: "POST",
            dataType: "html",
            url: "/Member/Discount/NewRule",
            data: data,
            cache: false,
            error: function () { $('#mainstatus').html('@RP.T("Admin.Common.ServerError")'); }
        }).done(function (data) {
            $('#newrulewrap').html(data);
            refreshList();
        });


    });
    var refreshList = function () {
        $.ajax({
            type: "GET",
            dataType: "html",
            url: "/Member/Discount/DiscountRuleList/" + $('#ID').val(),
            data: {},
            cache: false,
            error: function () { $('#mainstatus').html('@RP.T("Admin.Common.ServerError")'); }
        }).done(function (data) {
            $('#rulelist').html(data);

        });
    };

    refreshList();
</script>